name: Build
on: [ push ]
jobs:
  setup:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Make gradlew executable
        run: 'chmod +x ./gradlew'
      - name: Gradle build
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
        run: './gradlew clean build'
      - name: Publish to Maven Central
        if: github.ref == 'refs/heads/main'
        run: './gradlew publish'
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
